name: build-windows
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE
        run: |
          pyinstaller -w -F --name InvoiceAgentLite --add-data "data;data" launch.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: InvoiceAgentLite_win_exe
          path: dist/InvoiceAgentLite.exe
      - name: Build Installer (Inno Setup)
        shell: pwsh
        run: |
          choco install -y innosetup
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: InvoiceAgentLite_Setup
          path: Output/*.exe
